version: '3'

networks:
  kasm_default_network:
    external: true

services:

  cmmc-exporter:
    container_name: cmmc-exporter
    image: rahulosp/custom-exporter:1.4
    ports:
      - "0.0.0.0:8000:8000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/hostname:/etc/hostname:ro
      - /home/ansible/ansible.log:/usr/src/app/ansible.log  # Replace this with just /var/log/syslog or any random file if it is not Ansible. This will only be used on Ansible VMs
