version: '3'

networks:
  kasm_default_network:
    external: true

services:

  cmmc-exporter:
    container_name: cmmc-exporter
    image: rahulosp/custom-exporter:1.0
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/hostname:/etc/hostname:ro
    networks:
      - kasm_default_network
